language: c++
compiler: clang

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: BUILD_TYPE='DEBUG'

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -Wdev
  - cd Build

script:
  - make -j
  - ctest -V -j