language: c++
compiler: clang

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: BUILD_TYPE='DEBUG' PLATFORM_CMAKE_OPTION='-OPENSSL_ROOT_DIR=/usr/local/opt/openssl -DFOLLY_HAVE_WEAK_SYMBOLS=ON'

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - bash ./third_party/folly/folly/build/bootstrap-osx-homebrew.sh
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${PLATFORM_CMAKE_OPTION} -Wdev
  - cd Build

script:
  - make -j
  - ctest -V -j