language: c++

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - boost
            - cmake
            - gflags
            - git
            - glog
            - libevent
            - libtool
            - lz4
            - double-conversion
            - openssl
            - snappy
            - xz
            - zlib
      compiler: clang
      env: BUILD_TYPE='DEBUG' PLATFORM_CMAKE_OPTION='-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DFOLLY_HAVE_WEAK_SYMBOLS=ON'

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++
            - cmake
            - libboost-all-dev
            - libevent-dev
            - libdouble-conversion-dev
            - libgoogle-glog-dev
            - libgflags-dev
            - libiberty-dev
            - liblz4-dev
            - liblzma-dev
            - libsnappy-dev
            - make
            - zlib1g-dev
            - binutils-dev
            - libjemalloc-dev
            - libssl-dev
            - pkg-config
      compiler:
        - gcc
      env: BUILD_TYPE='DEBUG'


before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake -H. -BBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${PLATFORM_CMAKE_OPTION} -Wdev
  - cd Build

script:
  - make
  - ctest