name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: show third party libs
        run: ls -l third_party/folly && ls -l third_party/fizz && ls -l third_party/wangle
      - name: run ubuntu_setup.sh
        run:  sudo bash ./scripts/ubuntu_setup.sh
      - name: install folly
        run: sudo bash ./scripts/install_folly.sh
      - name: install fizz
        run: sudo bash ./scripts/install_fizz.sh
      - name: install wangle
        run: sudo bash ./scripts/install_wangle.sh
      - name: compile project
        run: mkdir _build && cd _build && cmake -DBUILD_TYPE=debug .. && make