name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0
      - name: show third party libs
        run: ls -l third_party/folly && ls -l third_party/fizz && ls -l third_party/wangle
      - name: run ubuntu_setup.sh
        run:  sudo bash ./scripts/ubuntu_setup.sh
      - name: install folly
        run: sudo bash ./scripts/install_folly.sh
      - name: install fizz
        run: sudo bash ./scripts/install_fizz.sh
      - name: install wangle
        run: sudo bash ./scripts/install_wangle.sh
      - name: mkdir minigame install dir
        run: mkdir minigame_sevrer_install
      - name: compile project && install
        run: mkdir _build && cd _build && cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=minigame_server_install .. && make install
      - name: publish minigame docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: xinnjie/minigame
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          snapshot: true
